language: python
python:
  - "3.7"
  - "3.8"
  - "nightly"
install:
  - "pip install -r requirements.txt"
  - "python setup.py -q install"
script:
  - "cd json_preprocessor/test"
  - "python test_json_preprocessor.py"

